services:
  - type: web
    name: betterhabit
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: betterhabit
          property: port
      - key: WEB_APP_URL
        value: https://one-better.onrender.com
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_c4Ihv9jBLuEP@ep-plain-sound-ab39we88-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require

# Agar PostgreSQL database kerak bo'lsa, quyidagi qismni oching:
# databases:
#   - name: betterhabit-db
#     plan: free
#     databaseName: betterhabit
#     user: betterhabit

